### ISSUE TITLE
Inconsistent use of BLOCK_SKIP_READ's name in PERSISTENT_DATA_Unmarshal

### ISSUE THREAD

**Issue by fishilico** [stefanberger/libtpms#177]
**Describe the bug**
In function `PERSISTENT_DATA_Unmarshal` in <https://github.com/stefanberger/libtpms/blob/901c9a76c79cc60413484ea5d9b0ee425b7c559d/src/tpm2/NVMarshal.c>, the `name` parameter of `BLOCK_SKIP_READ` takes several different values:

```c
// Line 3929
        BLOCK_SKIP_READ(skip_num_policy_pcr_group, needs_block, buffer, size,
                        "PERSISTENT_DATA", "pcrPolicies");
// Line 4038
        BLOCK_SKIP_READ(skip_future_versions, hdr.version >= 3, buffer, size,
                        "Volatile State", "version 3 or later");
// Line 4042
        BLOCK_SKIP_READ(skip_future_versions, hdr.version >= 4, buffer, size,
                        "PERSISTENT DATA", "version 4 or later");
// Line 4058
        BLOCK_SKIP_READ(skip_future_versions, FALSE, buffer, size,
                        "PERSISTENT DATA", "version 5 or later");
```

The use of `"Volatile State"` is likely a copy-paste error, and using both `"PERSISTENT_DATA"` (with an underscore) and `"PERSISTENT DATA"` (with no underscore) is inconsistent.

**To Reproduce**
1. Open `src/tpm2/NVMarshal.c`
2. Search for `BLOCK_SKIP_READ` in function `PERSISTENT_DATA_Unmarshal`
3. Observe the name parameter of this macro

**Expected behavior**
I expect that all invocations of `BLOCK_SKIP_READ` in `PERSISTENT_DATA_Unmarshal` use the same name.

**Versions of relevant components**
- libtpms: `master` (as well as some previous versions).

**Additional context**
I was trying to understand the content of the file which stores the persistent data of the TPM used by `swtpm` when I stumbled upon this inconsistency.

**Comment by stefanberger** [comment]
@fishilico Thanks for reporting this. I opened PR #178 to address these issues.

**Comment by fishilico** [comment]
Thanks! I see that you found more similar issues in `NVMarshal.c` and created both https://github.com/stefanberger/libtpms/pull/178 to fix them in `master`, and https://github.com/stefanberger/libtpms/pull/179 for branch `stable-0.7.0`

**Comment by stefanberger** [comment]
If you want I can add your Reported-by: to the patches. Just type it here if you want. Let me know.

**Comment by fishilico** [comment]
> If you want I can add your Reported-by: to the patches. Just type it here if you want. Let me know.

You can use `Reported-by: Nicolas Iooss <nicolas.iooss@ledger.fr>`. Thanks :)

**Comment by stefanberger** [comment]
Done. Will merge once the tests have run through again.

**Comment by stefanberger** [comment]
Merge now. Closing the issue.
