### ISSUE TITLE
Windows support for TPM2_ContextSave & TPM2_ContextLoad on 0.8.x

### ISSUE THREAD

**Issue by neacsu** [stefanberger/libtpms#217]
**Bug description**
When running `TPM2_ContextSave` followed by a `TPM2_ContextLoad` inside a Windows guest in qemu as part of a `certreq` command, the `TPM2_ContextLoad` fails.

The reason for this seems to be that the Windows driver sends a context padded until `TPM_PT_MAX_OBJECT_CONTEXT` when issuing `TPM2_ContextLoad`, even though `TPM2_ContextSave` responded with a context smaller than `TPM_PT_MAX_OBJECT_CONTEXT`.

**To Reproduce**
1. Start a Windows guest in qemu:
```
qemu-system-x86_64 -hda /home/fedora/vm-store/server-2019.qcow2 \
-boot d \
-cdrom /home/fedora/vm-store/Windows_2019_Server.iso \
-vnc 127.0.0.1:0,password \
-m 8192 \
-enable-kvm \
-monitor stdio \
-chardev socket,id=chrtpm,path=/home/fedora/vm-store/tpm-state/swtpm-sock \
-tpmdev emulator,id=tpm0,chardev=chrtpm -device tpm-tis,tpmdev=tpm0 \
-nic user,hostfwd=tcp::3389-:3389,hostfwd=tcp::1771-:1771,hostfwd=tcp::137-:137,hostfwd=udp::137-:137,hostfwd=udp::138-:138,hostfwd=tcp::139-:139
```
2. Setup a certificate authority following these instructions: https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/component-updates/tpm-key-attestation 
3. Run `certreq -q -enroll TPM_KEY` inside the Windows guest

**Expected behavior**
`certreq` command should succeed in issuing the certificate. Other `TPM2_ContextSave` & `TPM2_ContextLoad` valid workflows should succeed as well under Windows guests.

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 33

**Versions of relevant components**
- libtpms: 0.8.2
- swtpm: 0.5.2

**Additional context**
The first encounter of this problem was during a test run of HLK Windows test suite.

The commit that triggers this seems to be https://github.com/stefanberger/libtpms/commit/1e1648fec31bd8d80b2ece4eaefe851e2cf4009d .

**Comment by stefanberger** [comment]
Can you be a bit more specific about the HLK test that failed? I have not heared about an HLK test failure regarding context loads/saves.

**Comment by stefanberger** [comment]
> The reason for this seems to be that the Windows driver sends a context padded until `TPM_PT_MAX_OBJECT_CONTEXT` when issuing `TPM2_ContextLoad`, even though `TPM2_ContextSave` responded with a context smaller than `TPM_PT_MAX_OBJECT_CONTEXT`.

Thanks, that's helpful. Any hint on which part is padded and where in the libtpms code it is failing? I haven't seen any such failure so far. Linux for sure doesn't add padding and other versions of Windows may not have hit this error, either.

**Comment by neacsu** [comment]
> Can you be a bit more specific about the HLK test that failed? I have not heared about an HLK test failure regarding context loads/saves.

It's the `TpmPerformanceTest::CertifyTest` from `TPM 2.0 Quality Test`.

Here is a snippet from the TraceLog:
```
00076786    drv    4    268    2    0    05\05\2021-21:47:04:339     ERROR tpm20-commands.cpp(151) ?Tpm20CmdContextLoad@@YAJPEAVTpmTransport@@IPEAU_TPM20_CONTEXT_BLOB_CMD@@PEAT_TPM20_HANDLE@@@Z:Unexpected response to TPM20_CC_ContextLoad. ST=0x8001, size=0xa, RC=0x95
00076787    drv    4    268    2    0    05\05\2021-21:47:04:339     ERROR rm20-resourcemgr.cpp(1817) ?LoadObject@Tpm20ResourceMgr@@AEAAJPEAVTpm20Resource@@IPEAPEAV2@@Z:Could not load virtual resource 0x80fff7ad: 0xc0000186(STATUS_DEVICE_PROTOCOL_ERROR)
00076788    drv    4    268    2    0    05\05\2021-21:47:04:339     ERROR sched20.cpp(1824) ?DoUserRequest@Tpm20Scheduler@@AEAAXXZ:TPM submit failed: status=c0000186
```

> Any hint on which part is padded and where in the libtpms code it is failing? 

The context part of the buffer is padded. Basically, the `TPM2_ContextSave` response is 1264 bytes, from which the last 1254 are the context blob.
Later Windows does a `TPM2_ContextLoad` request with 2702 bytes, from which the first 10 bytes are a correctly formatted header (especially in terms of `commandSize`), followed by the 1254 bytes from the context blob, and the rest is just seemingly unrelated bytes. At this point, libtmps fails when unmarshalling the given context, though I am not sure where exactly in the code that happens.

> Linux for sure doesn't add padding

Yes, from what I've tested, the Linux behavior seems to be fine for these commands.

**Comment by stefanberger** [comment]
I am currently busy with some other stuff and will get to this once I am done with that. So any more investigations or even debugging you can do will help a lot.

> It's the TpmPerformanceTest::CertifyTest from TPM 2.0 Quality Test.

Thanks. 

> Later Windows does a `TPM2_ContextLoad` request with 2702 bytes, from which the first 10 bytes are a correctly formatted header (especially in terms of `commandSize`), followed by the 1254 bytes from the context blob, and the rest is just seemingly unrelated bytes. At this point, libtmps fails when unmarshalling the given context, though I am not sure where exactly in the code that happens.

So you are saying it cannot unmarshal the previously saved context, so ANY_OBJECT_Unmarshal is failing? it's not just additional bytes appended to the end but something even more 'corrupt' than that?

**Comment by stefanberger** [comment]
```
00076786    drv    4    268    2    0    05\05\2021-21:47:04:339     ERROR tpm20-commands.cpp(151) ?Tpm20CmdContextLoad@@YAJPEAVTpmTransport@@IPEAU_TPM20_CONTEXT_BLOB_CMD@@PEAT_TPM20_HANDLE@@@Z:Unexpected response to TPM20_CC_ContextLoad. ST=0x8001, size=0xa, RC=0x95
```

If 0x95 is a return from the TPM 2 then this would mean: `TPM_RC_SIZE - structure is the wrong size Handle number unspecified`
That would be scary!

**Comment by stefanberger** [comment]
Win 10 - 2004 does not show this issue.

**Comment by stefanberger** [comment]
How did you install he HLK client on the 2019 server test machine? I don't seem to be able to follow the instruction nor does it seem to be straight forward to get the client tool to work.

**Comment by stefanberger** [comment]
I am using the IBM TSS2 tools (with tpmproxy) now and can recreate the issue.

The error occurs because of this part [here](https://github.com/stefanberger/libtpms/blob/v0.8.2/src/tpm2/CommandDispatcher.c#L337-L342):

```
    // Should have used all the bytes in the input
    if(command->parameterSize != 0)
	{
	    result = TPM_RC_SIZE;
	    goto Exit;
	}
```


The way libtpms is serializing the keys is that it doesn't create a fixed-sized object and therefore leaves 1434 bytes over (in my test case) due to this padding, which triggers the above error. I don't understand the wisdom behind the padding. It sounds more like a bug.

**Comment by stefanberger** [comment]
Didn't mean to close the issue...

**Comment by stefanberger** [comment]
Note: Set breakpoint in `TPMS_CONTEXT_Unmarshal`.

1. Create 4 primary keys: `ceateprimary -hi o -st`
2. Create a key: `create -hp 80ffffff -st`   --> should hit breakpoint

**Comment by stefanberger** [comment]
Can you test the following proposed patch? Are there any other issues with HLK?
```
From dfdef16d827b8280518fffb6e997183f7cd81136 Mon Sep 17 00:00:00 2001
From: Stefan Berger <stefanb@linux.vnet.ibm.com>
Date: Fri, 28 May 2021 18:32:25 -0400
Subject: [PATCH] tpm2: Consume padding bytes in TPM2_ContextLoad() (Win2k19,
 issue #217)

Windows 2019 Server padds the TPMS_CONTEXT with additional bytes up to
TPM_PT_MAX_OBJECT_CONTEXT when sending a TPM2_ContextLoad even if less
bytes were returned in TPM2_ContextSave. Since libtpms does not use an
OBJECT to serialize the keys (anymore) it now uses less bytes than the
MAXimum of TPM_PT_MAX_OBJECT_CONTEXT bytes and the padding leaves some
unconsumed bytes that end up failing the command since no left-over
bytes are allowed in any command.

When unconsumed bytes are left in TPMS_CONTEXT_Unmarshal we check that
the original passed in size was TPM_PT_MAX_OBJECT_CONTEXT and only then
consume the additional padding bytes. Luckily also only one command
calls TPMS_CONTEXT_Unmarshal so that no side effects should occur.

The wisdom behind the padding is not quite clear but it feels like
ill-fixing the code to make Windows 2019 server work...

This patch fixes issed #217

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>
---
 src/tpm2/Unmarshal.c | 29 +++++++++++++++++++++++++++++
 1 file changed, 29 insertions(+)

diff --git a/src/tpm2/Unmarshal.c b/src/tpm2/Unmarshal.c
index 9aad24c..b836f05 100644
--- a/src/tpm2/Unmarshal.c
+++ b/src/tpm2/Unmarshal.c
@@ -4301,6 +4301,7 @@ TPM_RC
 TPMS_CONTEXT_Unmarshal(TPMS_CONTEXT *target, BYTE **buffer, INT32 *size)
 {
     TPM_RC rc = TPM_RC_SUCCESS;
+    INT32 orig_size = *size; // libtpms added

     if (rc == TPM_RC_SUCCESS) {
        rc = UINT64_Unmarshal(&target->sequence, buffer, size);
@@ -4314,6 +4315,34 @@ TPMS_CONTEXT_Unmarshal(TPMS_CONTEXT *target, BYTE **buffer, INT32 *size)
     if (rc == TPM_RC_SUCCESS) {
        rc = TPM2B_CONTEXT_DATA_Unmarshal(&target->contextBlob, buffer, size);
     }
+    // libtpms added begin
+    if (rc == TPM_RC_SUCCESS) {
+        if (*size > 0) {
+            /* Windows 2019 server pads the TPMS_CONTEXT up to TPM_PT_MAX_OBJECT_CONTENT
+             * and we end up with left-over padding bytes here that will make
+             * the TPM2_ContextLoad command fail. This is because we don't just write
+             * an OBJECT as the context but use ANY_OBJECT_Marshal to write it, which
+             * consumes less bytes. We had to do this due to a Linux TPM resource manager
+             * bug that couldn't deal with the larger context sizes and ran out of memory
+             * otherwise.
+             * Luckily only one command needs TPMS_CONTEXT unmarshalled, so we can adjust
+             * for the left-over padding here but also ONLY do this if
+             * 'orig_size' == value(TPM_PT_MAX_OBJECT_CONTENT)
+             */
+            static UINT32 tpm_pt_max_object_context;
+
+            if (tpm_pt_max_object_context == 0) {
+                TPML_TAGGED_TPM_PROPERTY tttp;
+
+                TPMCapGetProperties(TPM_PT_MAX_OBJECT_CONTEXT, 1, &tttp);
+                if (tttp.count == 1)
+                    tpm_pt_max_object_context = tttp.tpmProperty[0].value;
+            }
+            if ((UINT32)orig_size == tpm_pt_max_object_context)
+                *size = 0; /* consume the padding bytes */
+        }
+    }
+    // libtpms added end
     return rc;
 }

--
2.30.2

```

**Comment by marekkedzierski** [comment]
> 
> 
> Can you test the following proposed patch? Are there any other issues with HLK?
> 
> ```
> From 634e29b298a0877a05790ec28b44a09c30f89031 Mon Sep 17 00:00:00 2001
> From: Stefan Berger <stefanb@linux.vnet.ibm.com>
> Date: Fri, 28 May 2021 18:32:25 -0400
> Subject: [PATCH] tpm2: Consume padding bytes in TPM2_ContextLoad() (Win2k19,
>  issue #217)
> 
> Windows 2019 Server padds the TPM_ContextLoad() command with additional
> bytes up to TPM_PT_MAX_OBJECT_CONTEXT even if less bytes were returned
> in TPM2_ContextSave. Since libtpms does not use an OBJECT to serialize
> the keys (anymore) it now uses less bytes than the MAXimum of
> TPM_PT_MAX_OBJECT_CONTEXT bytes and the padding leaves some unconsumed
> bytes that end up failing the command since no left-over bytes are
> allowed in any command.
> 
> When unconsumed bytes are left in TPMS_CONTEXT_Unmarshal we check that
> the original passed in size was TPM_PT_MAX_OBJECT_CONTEXT and only then
> consume the additional padding bytes. Luckily also only one command
> calls TPMS_CONTEXT_Unmarshal so that no unwanted side effects should
> occur anywhere else.
> 
> The wisdom behind the padding is not quite clear but it feels like
> ill-fixing the code to make Windows 2019 server work...
> 
> This patch fixes issed #217
> 
> Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>
> ---
>  src/tpm2/Unmarshal.c | 29 +++++++++++++++++++++++++++++
>  1 file changed, 29 insertions(+)
> 
> diff --git a/src/tpm2/Unmarshal.c b/src/tpm2/Unmarshal.c
> index 9aad24c..b6bb44e 100644
> --- a/src/tpm2/Unmarshal.c
> +++ b/src/tpm2/Unmarshal.c
> @@ -4301,6 +4301,7 @@ TPM_RC
>  TPMS_CONTEXT_Unmarshal(TPMS_CONTEXT *target, BYTE **buffer, INT32 *size)
>  {
>      TPM_RC rc = TPM_RC_SUCCESS;
> +    INT32 orig_size = *size; // libtpms added
> 
>      if (rc == TPM_RC_SUCCESS) {
>         rc = UINT64_Unmarshal(&target->sequence, buffer, size);
> @@ -4314,6 +4315,34 @@ TPMS_CONTEXT_Unmarshal(TPMS_CONTEXT *target, BYTE **buffer, INT32 *size)
>      if (rc == TPM_RC_SUCCESS) {
>         rc = TPM2B_CONTEXT_DATA_Unmarshal(&target->contextBlob, buffer, size);
>      }
> +    // libtpms added begin
> +    if (rc == TPM_RC_SUCCESS) {
> +        if (*size > 0) {
> +            /* Windows 2019 server pads the TPMS_CONTEXT up to TPM_PT_MAX_OBJECT_CONTENT
> +             * and we end up with left-over padding bytes here that will make
> +             * the TPM2_ContextLoad command fail. This is because we don't just write
> +             * an OBJECT as the context but use ANY_OBJECT_Marshal to write it, which
> +             * consumes less bytes. We had to do this due to a Linux TPM resource manager
> +             * bug that couldn't deal with the larger context sizes and ran out of memory
> +             * otherwise.
> +             * Luckily only one command needs TPMS_CONTEXT unmarshalled, so we can adjust
> +             * for the left-over padding here but also ONLY do this if
> +             * 'orig_size' == value(TPM_PT_MAX_OBJECT_CONTENT)
> +             */
> +            static UINT32 tpm_pt_max_object_context;
> +
> +            if (tpm_pt_max_object_context == 0) {
> +                TPML_TAGGED_TPM_PROPERTY tttp;
> +
> +                TPMCapGetProperties(TPM_PT_MAX_OBJECT_CONTEXT, 1, &tttp);
> +                if (tttp.count == 1)
> +                    tpm_pt_max_object_context = tttp.tpmProperty[0].value;
> +            }
> +            if ((UINT32)orig_size == tpm_pt_max_object_context)
> +                *size = 0; /* consume the padding bytes */
> +        }
> +    }
> +    // libtpms added end
>      return rc;
>  }
> 
> --
> 2.30.2
> ```

I tested mentioned patch with Server 2019 and seems to be working. However I think that Microsoft
should take a look at this issue, because this error seems to be related to HLK 1809. On newest HLK (2004) 
this problem doesn't appear.

**Comment by stefanberger** [comment]
> I tested mentioned patch with Server 2019 and seems to be working. However I think that Microsoft
> should take a look at this issue, because this error seems to be related to HLK 1809 and Windows libraries. On newest Windows 10 with HLK 2004 this problem doesn't appear.

I agree that Microsfot should look at this. How do we know that they will actually fix it then if you were to file an issue with them and in what timeframe? So now I am wondering whether to apply the patch, even just temporarily...

**Comment by petreeftime** [comment]
The patch works for me as well on Windows 2016.

**Comment by stefanberger** [comment]
... likes like I should apply this patch ...

**Comment by stefanberger** [comment]
Fedora packages for testing on F33 and F34 should become available via links from this page: https://bodhi.fedoraproject.org/updates/?packages=libtpms

**Comment by stefanberger** [comment]
@neacsu Did you get a chance to try out the packages for fc34? https://bodhi.fedoraproject.org/updates/FEDORA-2021-ac32c2f635

**Comment by neacsu** [comment]
Sorry for the long delay. I tested the fix on Fedora and it works as expected: `The requested certificate has been issued`
Thank you for the quick patch. If that's ok with you, I will close the issue now.

**Comment by stefanberger** [comment]
@neacsu Thanks for coming back to it!
