### ISSUE TITLE
erroneous gitignore entries

### ISSUE THREAD

**Issue by mimir-d** [stefanberger/libtpms#249]
hi, just a quick note here

In v0.8.4 there was a change to gitignore adding "/man/man3/*.3"
The issue is that there are still files in the man3 directory that are being used in the makefile. Since these are already committed, they aren't ignore by git, but if the codebase is cloned, those start getting ignored and make fails (in my case "TPM_Free.3").

**Comment by mimir-d** [comment]
a couple more i found trying to import 0.7.8

? libtpms/dist/libtpms.spec
? libtpms/include/libtpms/tpm_library.h
? libtpms/m4/ax_check_define.m4
? libtpms/m4/ax_check_linker_flag.m4
? libtpms/tests/corpus-execute-command/01288b7552bfaf10ba3e65a18059a54a8bb257d0
? libtpms/tests/corpus-execute-command/0157ea12e541d38f4ef2a25e302428fa82612667
... (everything in this last folder)

**Comment by mimir-d** [comment]
im just gonna post this here, it's a similar situation with swtpm v0.6.0, these files are in gitignore but committed:

tests/patches/libtpm.patch
man/man8/swtpm_setup.sh.8
swtpm.spec
tests/patches/0002-Implement-powerup-for-swtpm.patch

**Comment by stefanberger** [comment]
> The issue is that there are still files in the man3 directory that are being used in the makefile. Since these are already committed, they aren't ignore by git, but if the codebase is cloned, those start getting ignored and make fails (in my case "TPM_Free.3").

Can you post the steps to recreate the failure, starting with the clone? Travis is building the branches upon every check-in and I also build them successfully on my machines, so I am wondering how you get to a build failure.

**Comment by mimir-d** [comment]
Ah... it's a bit more complicated. I'm actually importing the project in a mercurial repo that is configured to respect .gitignore. So it picks up the .gitignore and then drops the files because they match ignore rules. I don't think it's reproducible with just a git clone, since for git the files are already committed (despite being on the ignore list now).
I fixed this manually for the moment by forcing mercurial to add the files.

You can get a list of the ignored, committed files:
> git ls-files -i --exclude-standard
man/man8/swtpm_setup.sh.8
swtpm.spec
tests/patches/0001-Deactivate-test-cases-accessing-rootcerts.txt.patch
tests/patches/0002-Implement-powerup-for-swtpm.patch
tests/patches/0003-Set-CRYPTOLIBRARY-to-openssl.patch
tests/patches/0004-Store-and-restore-volatile-state-at-every-step.patch
tests/patches/0005-Disable-tests-related-to-events.patch
tests/patches/0006-Disable-testing-with-RSA-3072.patch
tests/patches/0007-Disable-rev155-test-cases.patch
tests/patches/0008-Disable-x509-test-cases.patch
tests/patches/0009-Disable-getcapability-TPM_CAP_ACT.patch
tests/patches/libtpm.patch

**Comment by stefanberger** [comment]
Please have a look at PR #250 which fixes the issue on the master branch.

**Comment by mimir-d** [comment]
Sorry, I fell off the face of the earth for a while. The PR looks ok, it's already merged so everything is fine. Thanks for addressing this

**Comment by stefanberger** [comment]
@mimir-d glad you're back.
