### ISSUE TITLE
The IETF doc uses a different IV in SM4 CTR

### ISSUE THREAD

**Issue by JerryDevis** [stefanberger/libtpms#252]
Hello, the test data of SM4 is from IEIF (https://tools.ietf.org/html/draft-ribose-cfrg-sm4-04#appendix-A.2). The Iv is inconsistent with libtpms，so do we need to modify the dataOut_SM4128_CTR or MakeIv founction?

**Comment by stefanberger** [comment]
Per Tpmprofile.h, SM4 is not officially supported in libtpms since it's disabled. So it's quite possible that the CTR part needs some fixing.

**Comment by stefanberger** [comment]
Btw, I cannot generally enable sm4 since it's not supported on many distros and I don't want to have diverging configuration files for distros enabling sm4 on one and disabling it on another. Also see #206.
