### ISSUE TITLE
Sequence object cannot be flushed, when TPM2_SequenceUpdate failed.

### ISSUE THREAD

**Issue by JerryDevis** [stefanberger/libtpms#253]
when I run the following tpm command using tpm2-tools, the error code is 0x103.
```
dd if=/dev/urandom of=hash.in count=1 bs=2093 2> /dev/null 
tpm2 pcrevent -Q -P foo hash.in
tpm2 flushcontext -t
```

I found it will flush sequence object in ExecuteCommand, when the evict attributes of object is set. However, when run TPM2_EventSequenceComplete, or TPM2_SequenceComplete, this evict attributes is set.  So it cannot be flushed, when  TPM2_SequenceUpdate failed.

**Comment by stefanberger** [comment]
Can you please also show the error output that you get at each of the above steps?

**Comment by stefanberger** [comment]
I tried this with this sequence here using the Intel TSS 2 tools and the IBM TSS 2 tools for flushing the context. I tried it on Fedora 34 with the following packages installed:

```
> rpm -q -a | grep tpm2
tpm2-tss-3.1.0-1.fc34.x86_64
clevis-pin-tpm2-0.3.0-1.fc34.x86_64
tpm2-pkcs11-tools-1.6.0-1.fc34.x86_64
tpm2-pkcs11-1.6.0-1.fc34.x86_64
tpm2-abrmd-selinux-2.3.1-3.fc34.noarch
tpm2-abrmd-2.4.0-3.fc34.x86_64
tpm2-tools-5.1.1-1.fc34.x86_64
> rpm -q -a | grep tss2
tss2-1.6.0-1.fc34.x86_64
```

```
> export TPM2TOOLS_TCTI="swtpm:port=2321"
> export TPM_COMMAND_PORT=2321 TPM_PLATFORM_PORT=2322   TPM_SERVER_NAME=localhost TPM_INTERFACE_TYPE=socsim   TPM_SERVER_TYPE=raw

> tpm2_startup -c

> tpm2 pcrevent -Q -P foo hash.in
WARNING:esys:src/tss2-esys/api/Esys_EventSequenceComplete.c:317:Esys_EventSequenceComplete_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_EventSequenceComplete.c:102:Esys_EventSequenceComplete() Esys Finish ErrorCode (0x000009a2) 
ERROR: Esys_EventSequenceComplete(0x9A2) - tpm:session(1):authorization failure without DA implications
ERROR: Unable to run pcrevent

> tpm2_getcap handles-transient
- 0x80000000

> tpm2_flushcontext 0x80000000
WARNING:esys:src/tss2-esys/api/Esys_ReadPublic.c:320:Esys_ReadPublic_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/esys_tr.c:231:Esys_TR_FromTPMPublic_Finish() Error ReadPublic ErrorCode (0x00000103) 
ERROR:esys:src/tss2-esys/esys_tr.c:321:Esys_TR_FromTPMPublic() Error TR FromTPMPublic ErrorCode (0x00000103) 
ERROR: Esys_TR_FromTPMPublic(0x103) - tpm:error(2.0): improper use of a sequence handle
ERROR: Unable to run tpm2_flushcontext

> tpm2_getcap handles-transient
- 0x80000000

> tssflushcontext -ha 0x80000000
flushcontext: failed, rc 000b0016
TSS_RC_FILE_REMOVE - A file remove failed

> tpm2_getcap handles-transient
```

This sequence shows that the handle can be flushed but requires the IBM TSS 2 tools to do so (which will emit an error because the context wasn't created with the IBM TSS 2 tools). To me it looks like the Intel TSS 2 tools need to be adjusted/fixed to properly clean up after this type of failure.

**Comment by stefanberger** [comment]
I think that this is also not a libtpms issue but an Intel TSS2 stack issue. Using the IBM TPM2 tools one can obviously get rid of the sequence handle. My guess is the Intel TSS2 stack may be missing support for this type of a handle.

**Comment by JerryDevis** [comment]
Ok，thanks
