### ISSUE TITLE
use docker to produce packages?

### ISSUE THREAD

**Issue by rgl** [stefanberger/libtpms#27]
does it make sense to have a dockerfile in this repository to build the various distributions packages? e.g. for ubuntu 18.04.

**Comment by stefanberger** [comment]
There are just so many different distributions and versions of them ...

**Comment by rgl** [comment]
I understand your concern. I will not do a pull request then. Instead I did it at https://github.com/rgl/libtpms/commit/562749df9b8e78ac1722977b5f8a4ab70d0912d8.

But I'm not being able to build `swtpm` at https://github.com/rgl/swtpm/commit/e10fe5ac9ce9b855b30539a10a444a71eab11a15, can you please look at the logs at https://gist.github.com/rgl/6e8dee7634dc4e2dfdba7559495d6ac7?

At the top of the [Dockerfile.ubuntu-18.04](https://github.com/rgl/swtpm/blob/master/Dockerfile.ubuntu-18.04) file I've places the commands that one need to execute to build with docker.

Please let me known if this conversation should be moved to the `swtpm` issue tracker.

**Comment by stefanberger** [comment]
If you don't mind I would take your Dockerfile and put it on the wiki referencing you as the author (or write in the Dockerfile ?).

**Comment by stefanberger** [comment]
Did you follow my suggestion of adding libssl-dev to BuildDepends in debian/control of swtpm? I think it's the missing piece.

**Comment by rgl** [comment]
Oh sorry, for some reason, I didn't see the notification about your suggestion. I close this issue and reply there.

**Comment by stefanberger** [comment]
I put your Dockerfile with 2 modifications here: https://github.com/stefanberger/libtpms/wiki/Dockerfiles

I needed to run `NOCONFIGURE=1 ./autogen.sh` before the package building, also in swptm. `swtpm` had a few more dependencies missing.

**Comment by stefanberger** [comment]
This swtpm PR https://github.com/stefanberger/swtpm/pull/105 should fix it.

**Comment by rgl** [comment]
Indeed, I've mentioned that on https://gist.github.com/rgl/6e8dee7634dc4e2dfdba7559495d6ac7 but seems none of us receives notifications on gists :-(

Can you please have a look at it?

**Comment by stefanberger** [comment]
Yes, I don't receive notifications from there, either. Left a message there...

**Comment by rgl** [comment]
Have a look at https://github.com/stefanberger/swtpm/compare/master...rgl:master as I'm making more changes to the make it work. E.g. libtpms vs libtpms0 and - - with-gnutls

Sorry to takeover this issue. But it's easier to talk in this issue due to notifications.
