### ISSUE TITLE
Typo in the preprocessor symbol name for gcc minor version

### ISSUE THREAD

**Issue by nbuwe** [stefanberger/libtpms#289]
https://github.com/stefanberger/libtpms/blob/aeb7af78a97b97cf739a0fad76b50356e2005e97/src/tpm2/CompilerDependencies.h#L131

references ` __GNUC_MINOR`.  The correct name is `__GNUC_MINOR__`.

Cf. https://gcc.gnu.org/onlinedocs/cpp/Common-Predefined-Macros.html

**Comment by stefanberger** [comment]
Thanks for reporting. Fixing it.
