### ISSUE TITLE
Support CC_ECC_Encrypt and CC_ECC_Decrypt

### ISSUE THREAD

**Issue by JerryDevis** [stefanberger/libtpms#291]
Hi, stefan. rev164 has support CC_ECC_Encrypt and CC_ECC_Decrypt commands, and the code  PR #292  are from [Trusted Platform Module Library Part 3: Commands](https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p64_Part3_Commands_code_15may2021.pdf) and [Trusted Platform Module Library Part 4: Supporting Routines](https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p64_Part4_SupportingRoutines_code_15may2021.pdf).

**Comment by stefanberger** [comment]
I saw your PR. It will be a while until I get to it since I am busy with other things. Is there anything that tests the encryption/decryption?

**Comment by JerryDevis** [comment]
> 

There are not ecc encryption and decryption tests code in TCG standard. But I am adding tests for this.

**Comment by JerryDevis** [comment]
> 

There are not ecc encryption and decryption tests code in TCG standard. But I am adding some tests for this.

**Comment by stefanberger** [comment]
I have added support for the new commands a while ago by sync'ing with 'my' upstream repo (Kenny Goldman's repo). The new commands will be enabled via profiles.
