### ISSUE TITLE
Future trouble: OpenSSL 3.x may require host admin to enable legacy mode to support SHA1 signatures

### ISSUE THREAD

**Issue by stefanberger** [stefanberger/libtpms#303]
**Describe the bug**

OpenSSL 3.x builds may require that a host admin enable legacy mode on the host so that applications can use SHA1 in relation to signatures. It's not currently clear whether this eliminates SHA1 entirely or only for signature creation or also for signature verification.

Due to upgradeability of libtpms state SHA1 cannot be disabled in libtpms.

Reference: Discussion here: https://bugzilla.redhat.com/show_bug.cgi?id=2061607

**Comment by stefanberger** [comment]
OpenSSL should have an API to enable SHA1 for applications that want to have it programmatically like it allows to load legacy modules programmatically:

[ Source: https://wiki.openssl.org/index.php/OpenSSL_3.0#Providers ]

```
  #include <stdio.h>
  #include <stdlib.h>
  
  #include <openssl/provider.h>
   
   int main(void)
   {
       OSSL_PROVIDER *legacy;
       OSSL_PROVIDER *deflt;
   
       /* Load Multiple providers into the default (NULL) library context */
       legacy = OSSL_PROVIDER_load(NULL, "legacy");
       if (legacy == NULL) {
           printf("Failed to load Legacy provider\n");
           exit(EXIT_FAILURE);
       }
       deflt = OSSL_PROVIDER_load(NULL, "default");
       if (deflt == NULL) {
           printf("Failed to load Default provider\n");
           OSSL_PROVIDER_unload(legacy);
           exit(EXIT_FAILURE);
       }
   
       /* Rest of application */
   
       OSSL_PROVIDER_unload(legacy);
       OSSL_PROVIDER_unload(deflt);
       exit(EXIT_SUCCESS);
   }
```

**Comment by stefanberger** [comment]
OpenSSL should have an API to enable SHA1 for applications that still want to use it programmatically for signature verification and signing. It already allows one to enable legacy crypto algorithms/modules programmatically:

[ Source: https://wiki.openssl.org/index.php/OpenSSL_3.0#Providers ]

```
  #include <stdio.h>
  #include <stdlib.h>
  
  #include <openssl/provider.h>
   
   int main(void)
   {
       OSSL_PROVIDER *legacy;
       OSSL_PROVIDER *deflt;
   
       /* Load Multiple providers into the default (NULL) library context */
       legacy = OSSL_PROVIDER_load(NULL, "legacy");
       if (legacy == NULL) {
           printf("Failed to load Legacy provider\n");
           exit(EXIT_FAILURE);
       }
       deflt = OSSL_PROVIDER_load(NULL, "default");
       if (deflt == NULL) {
           printf("Failed to load Default provider\n");
           OSSL_PROVIDER_unload(legacy);
           exit(EXIT_FAILURE);
       }
   
       /* Rest of application */
   
       OSSL_PROVIDER_unload(legacy);
       OSSL_PROVIDER_unload(deflt);
       exit(EXIT_SUCCESS);
   }
```

**Comment by stefanberger** [comment]
Fun facts about SHA-1 in TPM 2 code:

- Support for SHA-1 has been enabled a long time ago in the TPM 2 code: https://github.com/stefanberger/libtpms/blob/ccce8b5f4937e13dfd0a72d80169bac4ccebb633/src/tpm2/Implementation.h#L89
- SHA-1, just like any other algorithm, cannot just be disabled without breaking the upgrade path for vTPM users who rely on SHA-1
- When SHA1 is enabled, the SHA1 PCR bank is also enabled that the firmware and IMA may then use it and extend their measurements into the PCRs of that SHA-1 bank
- The SHA-1 is 'advertised' by the TPM 2 as a capability:
```
$ tssgetcapability -cap 0
33 algorithms 
   TPM_ALG_RSA
    TPMA_ALGORITHM: asymmetric
    TPMA_ALGORITHM: object
   TPM_ALG_TDES
    TPMA_ALGORITHM: symmetric
   TPM_ALG_SHA1
    TPMA_ALGORITHM: hash
   TPM_ALG_HMAC
    TPMA_ALGORITHM: hash
    TPMA_ALGORITHM: signing
[...]
```
It may be possible to suppress SHA-1 being advertised but this MUST NOT break the 'upgrade path'. So, applications that have used SHA-1 before must not break after an upgrade of the host system.

**Comment by elmarco** [comment]
Are enabled capabilities saved with the vTPM state? how/where?

Can we add options to selectively enable/disable TPM capabilities during manufacturing? (new swtpm_setup option)

**Comment by stefanberger** [comment]
> Are enabled capabilities saved with the vTPM state? how/where?

Capabilities are not stored with the TPM 2 state. They are derived from compile-time options.

> Can we add options to selectively enable/disable TPM capabilities during manufacturing? (new swtpm_setup option)

No. Just disabling capabilities doesn't help to keep an upgrade path alive. What OpenSSL seems to do is introduce failures into code paths when SHA-1 is being used. The solution is for OpenSSL to offer an API to programmatically enable legacy algorithms to maintain the upgrade path for those applications that need it. I have no answers on what to tell people when they upgrae form Fedora N to Fedora N+1 and  all of a sudden their SHA-1 signatures don't work anymoere. What do we tell them? Is won't-fix the answer?

**Comment by stefanberger** [comment]
> In other words, the only operation that is expected not to work, is when the TPM user actually attempts to perform a RSA SHA1 or ECDSA SHA1 signature, or verify such signature.

So then we don't do any change to libtpms TPM 2 code but tell people to enable the legacy crypto system-wide.

**Comment by tomato42** [comment]
Yes, if user needs to handle SHA-1 signatures they can just switch to LEGACY policy (`update-crypto-policies --set LEGACY` as root) and they will work again, allowing the user to migrate to something stronger. There should be no need for changes in libtpms code.

**Comment by elmarco** [comment]
> > Can we add options to selectively enable/disable TPM capabilities during manufacturing? (new swtpm_setup option)
> 
> No. Just disabling capabilities doesn't help to keep an upgrade path alive. What OpenSSL seems to do is introduce failures into code paths when SHA-1 is being used. The solution is for OpenSSL to offer an API to programmatically enable legacy algorithms to maintain the upgrade path for those applications that need it. I have no answers on what to tell people when they upgrae form Fedora N to Fedora N+1 and all of a sudden their SHA-1 signatures don't work anymore. What do we tell them? Is won't-fix the answer?

Such swtpm_setup option would be really useful though, even if only for testing. Furthermore, it's relatively easy to introduce incompatible libtpms (compiled with different capabilities), so saving the associated capabilities with the state should help. We should also leave room for future caps.

**Comment by stefanberger** [comment]
> Such swtpm_setup option would be really useful though, even if only for testing. Furthermore, it's relatively easy to introduce incompatible libtpms (compiled with different capabilities), so saving the associated capabilities with the state should help. We should also leave room for future caps.

Any modification to the compile-time options leads to an unsupported configuration as stated here:
https://github.com/stefanberger/libtpms/blob/master/src/tpm2/TpmProfile.h#L62-L63

I cannot support arbitrary configurations.

These capabilities are compile-time options that cannot just be disabled during runtime. The compile time options play into exchanging of state of the TPM between versions of distros, upgrade path, migration story etc.

All these capabilities (compile time options) are stored in the state of the vTPM and must match those of a running instance of the TPM (no modifications allowed) so that the state is acceptable when it is read. We don't want to do a VM suspend while doing an RSA-SHA1 sign operation and after the resume have a vTPM that cannot verify what you previously signed.

https://github.com/stefanberger/libtpms/blob/master/src/tpm2/NVMarshal.c#L3673-L3805

**Comment by stefanberger** [comment]
Closing this now. For now we have the environment variable OPENSSL_ENABLE_SHA1_SIGNATURES to allow SHA1 signatures.
