### ISSUE TITLE
tpm_state_path may be null

### ISSUE THREAD

**Issue by setharnold** [stefanberger/libtpms#313]
https://github.com/stefanberger/libtpms/blob/5bc860ac3782969fd90b37367ebc6691b41c8c68/src/tpm_nvfile.c#L129

Hello, cppcheck has suggested that `tpm_state_path` may be NULL when it is passed to `strlen()` and `strcpy()` in case the `#ifdef` is not followed.

Thanks

**Comment by stefanberger** [comment]
Fixed.

**Comment by setharnold** [comment]
Ha :) that's awesome. It's not super-relevant to this specific bug, but I did finish my quick review, https://bugs.launchpad.net/ubuntu/+source/libtpms/+bug/1948748 in case you're curious. Thanks for the quick turnaround on even these low-priority sorts of things, it's very reassuring. :)

Thanks
