### ISSUE TITLE
Compilation fails on OSS-Fuzz

### ISSUE THREAD

**Issue by elmarco** [stefanberger/libtpms#317]
A new compilation error appeared:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46483

Step #12 - "compile-honggfuzz-address-x86_64": In file included from /src/libtpms/src/tpm_debug.c:42:
Step #12 - "compile-honggfuzz-address-x86_64": /src/libtpms/src/tpm_debug.h:69:9: error: 'printf' macro redefined [-Werror,-Wmacro-redefined]
Step #12 - "compile-honggfuzz-address-x86_64": #define printf(...) TPMLIB_LogPrintf(__VA_ARGS__);
Step #12 - "compile-honggfuzz-address-x86_64":         ^
Step #12 - "compile-honggfuzz-address-x86_64": /usr/include/x86_64-linux-gnu/bits/stdio2.h:110:11: note: previous definition is here
Step #12 - "compile-honggfuzz-address-x86_64": #  define printf(...) \
Step #12 - "compile-honggfuzz-address-x86_64":           ^
Step #12 - "compile-honggfuzz-address-x86_64": 1 error generated.
Step #12 - "compile-honggfuzz-address-x86_64": make[2]: *** [Makefile:2018: libtpms_la-tpm_debug.lo] Error 1
Step #12 - "compile-honggfuzz-address-x86_64": make[2]: *** Waiting for unfinished jobs....

It seems like a bad idea to "#define printf". Any chance we can replace all `printf()` occurences with `TPMLIB_LogPrintf()` instead? Or is the code in src/tpm12 still imported regularly from outside?

**Comment by stefanberger** [comment]
PR #319 resolved the issue: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46483#c1
