### ISSUE TITLE
Can't compile since latest git pull

### ISSUE THREAD

**Issue by mijk84** [stefanberger/libtpms#345]
make  all-recursive
make[1]: Entering directory '/home/mike/build/swtpm'
Making all in include
make[2]: Entering directory '/home/mike/build/swtpm/include'
Making all in swtpm
make[3]: Entering directory '/home/mike/build/swtpm/include/swtpm'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/mike/build/swtpm/include/swtpm'
make[3]: Entering directory '/home/mike/build/swtpm/include'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/mike/build/swtpm/include'
make[2]: Leaving directory '/home/mike/build/swtpm/include'
Making all in man
make[2]: Entering directory '/home/mike/build/swtpm/man'
Making all in man3
make[3]: Entering directory '/home/mike/build/swtpm/man/man3'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/mike/build/swtpm/man/man3'
Making all in man5
make[3]: Entering directory '/home/mike/build/swtpm/man/man5'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/mike/build/swtpm/man/man5'
Making all in man8
make[3]: Entering directory '/home/mike/build/swtpm/man/man8'
make[3]: Leaving directory '/home/mike/build/swtpm/man/man8'
make[3]: Entering directory '/home/mike/build/swtpm/man'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/mike/build/swtpm/man'
make[2]: Leaving directory '/home/mike/build/swtpm/man'
Making all in samples
make[2]: Entering directory '/home/mike/build/swtpm/samples'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/mike/build/swtpm/samples'
Making all in src
make[2]: Entering directory '/home/mike/build/swtpm/src'
Making all in utils
make[3]: Entering directory '/home/mike/build/swtpm/src/utils'
  CC       libswtpm_utils_la-swtpm_utils.lo
  CCLD     libswtpm_utils.la
make[3]: Leaving directory '/home/mike/build/swtpm/src/utils'
Making all in swtpm
make[3]: Entering directory '/home/mike/build/swtpm/src/swtpm'
  CC       swtpm-main.o
  CC       swtpm-daemonize.o
  CC       swtpm-swtpm.o
  CC       swtpm-swtpm_chardev.o
  CC       swtpm-cuse_tpm.o
  CC       libswtpm_libtpms_la-capabilities.lo
  CC       libswtpm_libtpms_la-common.lo
  CC       libswtpm_libtpms_la-ctrlchannel.lo
  CC       libswtpm_libtpms_la-fips.lo
fips.c: In function ‘fips_mode_enabled’:
fips.c:60:16: error: implicit declaration of function ‘EVP_default_properties_is_fips_enabled’ [-Werror=implicit-function-declaratio
]
   60 |     int mode = EVP_default_properties_is_fips_enabled(NULL);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [Makefile:792: libswtpm_libtpms_la-fips.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/home/mike/build/swtpm/src/swtpm'
make[2]: *** [Makefile:416: all-recursive] Error 1
make[2]: Leaving directory '/home/mike/build/swtpm/src'
make[1]: *** [Makefile:480: all-recursive] Error 1
make[1]: Leaving directory '/home/mike/build/swtpm'
make: *** [Makefile:408: all] Error 2

**Comment by stefanberger** [comment]
try `touch configure.ac && make`

**Comment by mijk84** [comment]
It didn't work. Should I be doing a clean clone and not run autogen.sh?

**Comment by stefanberger** [comment]
Try running autogen.sh. Basically the `touch configure` should have resolve the issue.

I suppose you have OpenSSL 3.x on your system? If nothing works can you have a look in /usr/include/openssl/evp.h whether you find `EVP_default_properties_is_fips_enabled` there?

**Comment by stefanberger** [comment]
I saw it now also on Ubuntu. It doesn't happen on Fedora.
