### ISSUE TITLE
Reason for mixed tabs and spaces?

### ISSUE THREAD

**Issue by collin-kemper** [stefanberger/libtpms#460]
Excerpt from EACommands.c, with the tab character replaced with `--->`:
```
    // Do validation for non trial session
    if(session->attributes.isTrialPolicy == CLEAR)
--->{
--->    // Make sure that this is not going to invalidate a previous PCR check
--->    if(session->pcrCounter != 0 && session->pcrCounter != gr.pcrCounter)
--->--->return TPM_RC_PCR_CHANGED;

--->    // If the caller specified the PCR digest and it does not
--->    // match the current PCR settings, return an error..
--->    if(in->pcrDigest.t.size != 0)
--->--->{
--->--->    if(!MemoryEqual2B(&in->pcrDigest.b, &pcrDigest.b))
--->--->--->return TPM_RCS_VALUE + RC_PolicyPCR_pcrDigest;
--->--->}
--->}
    else
--->{
--->    // For trial session, just use the input PCR digest if one provided
--->    // Note: It can't be too big because it is a TPM2B_DIGEST and the size
--->    // would have been checked during unmarshaling
--->    if(in->pcrDigest.t.size != 0)
--->--->pcrDigest = in->pcrDigest;
--->}
```

I know that "tabs vs. spaces" is sort of the archetypal pedantic complaint, but mixing them inconsistently breaks code editors with different tab widths (and multi-line editing). I have no preferences between tabs and spaces, (or even mixed them in lines if they are consistently used within columns).

**Comment by stefanberger** [comment]
The reference code I based this on uses tabs for 8 spaces, so your editor needs tabs set to 8 spaces to look good no matter what.

**Comment by stefanberger** [comment]
My 'upstream' repo that I am sync'ing changes with is here: https://sourceforge.net/p/ibmswtpm2/tpm2/ci/master/tree/
