### ISSUE TITLE
seg fault in tpm2_preview.rev138 code

### ISSUE THREAD

**Issue by mihaiserb** [stefanberger/libtpms#6]
While testing the tpm2_preview.rev138 code (called from a swtpm interface), I encountered a seg fault in SessionProcess.c (line 585).

The fault is triggered by a TPM2_Startup command (launched from swtpm_bios). It seems that an incorrect hash algo ID is provided (somehow) there. Is this a known issue?

I have not yet tested the tpm2_preview.rev142 code.

**Comment by stefanberger** [comment]
Please move to the tpm2_preview.rev142 code. That version will not be able to read the state from a previous version and will again change itself, but if we want to do fixes somewhere then it's in that latest version.  It's not a known issue from what I know. Can you tell me the sequence of commands you sent?

**Comment by mihaiserb** [comment]
I followed these steps:
- launch cuse_swtpm linked to tpm2_preview.rev138 libtpms (success)
- swtpm_ioctl -i /dev/<cuse-dev-node> (success)
- swtpm_bios --tpm-device /dev/<cuse-dev-node> -c (seg fault!)

If rev142 is the branch that will be further developed, I will try to re-test on it and return with the results.

**Comment by mihaiserb** [comment]
Perhaps it is something wrong in my setup. Will switch to the new branch and continue testing there.

I will use your commands to perform the tests.

Thanks!
