### ISSUE TITLE
SM2/3/4 algorithm support

### ISSUE THREAD

**Issue by liujiong63** [stefanberger/libtpms#86]
Hi stefanberger,

Are SM2/3/4 algorithms supported in libtpms and swtpm? If not, what's the best way to implement SM2/3/4 in libtpms and swtpm?

thanks!

**Comment by stefanberger** [comment]
SM2 is enabled, SM3/4 are not. To try a compilation with them one would need to enable them like this:

```
diff --git a/src/tpm2/Implementation.h b/src/tpm2/Implementation.h
index 740ce8a4..81aa6085 100644
--- a/src/tpm2/Implementation.h
+++ b/src/tpm2/Implementation.h
@@ -280,8 +280,8 @@
 #define ALG_SHA384                      ALG_YES
 #define ALG_SHA512                      ALG_YES
 #define ALG_SM2                         (ALG_YES && ALG_ECC) /* libtpms enabled */
-#define ALG_SM3_256                     ALG_NO
-#define ALG_SM4                         ALG_NO
+#define ALG_SM3_256                     ALG_YES
+#define ALG_SM4                         ALG_YES
 #define ALG_SYMCIPHER                   ALG_YES
 #define ALG_TDES                        ALG_YES              /* libtpms enabled */
 #define ALG_XOR                         ALG_YES
```

This leads to lots of compilation errors. OpenSSL may not have support for them (depending on distro) and a low-level implementation of these crypto algorithm is also missing.

**Comment by liujiong63** [comment]
Thanks, stefanberger! How to add the missing algorithms implementation? Any suggestion?

**Comment by stefanberger** [comment]
You should look at how for example AES is implemented (when we are not using the OpenSSL functions for it) and add the SM3/4 in a similar way plus test cases to verify that they produce the expected results.
