### ISSUE TITLE
libtpms Docker WIKI

### ISSUE THREAD

**Issue by ferdinan4** [stefanberger/libtpms#94]
Hi Stefan!

I'm having some issues trying to understand how the libtpms works. I am trying to create a docker enviroment in order to fuzzing but when I try to run the Example that you have in the wiki from @ruilopez it generates an error with mk-build-deps.

**E: You must put some 'source' URIs in your sources.list
mk-build-deps: Unable to find package name in `apt-cache showsrc debian/control'**

In addition, do you have any extended documentation that help me to understand how libtpms works?

Thanks in advance

Fernando

**Comment by stefanberger** [comment]
There are the man pages that describe the API of libtpms. The internals are largely standard TPM 1.2 and TPM 2.0 except for how state of the TPM 2 is written and read when the callbacks of the API are used. swtpm and test cases show how libtpms can be used. What exactly are you looking for ?

When running that `build.sh` from the libtpms/ directory on a Ubuntu 16.04 host, it builds fine for me.

**Comment by ferdinan4** [comment]
I am trying to building that dockerfile on my Ubuntu 18.04 hosts, it gives me an error, after add the package **libssl-dev** in the Dockerfile, it is compile well.

My architecture is:
We I have 2 different containers in Dockers, connected by socket TCP/IP.
             1 container) I have installed SWTPM 

             2 contanier) I have installed IBM tss. 

I have communication between them, but I would like to know which paper is taking libtpms in the communication in order to understand better all the process.

I am only interesting in tpm 2.0. 

Thanks in advance.

Fernando

**Comment by stefanberger** [comment]
I am not really sure what you are asking for. Which internals are interesting to you?

**Comment by ferdinan4** [comment]
I wanna understand for example, when I execute the command **tsspcrread -ha 10
** in the **TSS**, how libtpms capture that command and send the information to the swtpm and return  values of the PCR readed.

**Comment by stefanberger** [comment]
tsspcrread creates the TPM 2.0 command as a byte array and sends it to swtpm. swtpm will pass this byte array to libtpms using the TPMLIB_Process() call, which then inside libtpms gets passed to the TPM 2.0 code. The TPM 2.0 code parses the packet and acts on it and creates a response, which TPMLIB_Process then returns to swtpm. Swtpm then returns this response to the TSS.

**Comment by ferdinan4** [comment]
MANY THANKS!
